# Generated by Django 5.2.4 on 2025-07-03 14:20

import django.db.models.deletion
import goal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('deadline', models.DateField()),
                ('friendEmail', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('self_completed', 'Self Completed')], default='active', max_length=20)),
                ('verification_token', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, goal.models.GoalMixin),
        ),
    ]
